---
downloads: ~/.ansible-downloads/

projects_path: ~/Documents/Projects

dotfiles_repository: https://github.com/YentlFrickx/dotfiles.git

# files/directories located in ~/
dotfiles: 
  - .osx
  - .tmux.conf
  - .vimrc
  - .ssh
  - .zshrc

homebrew_taps:
  - homebrew/core
  - homebrew/cask-fonts

homebrew_use_brewfile: false
homebrew_cask_apps:
  - 1password
  - appcleaner
  - betterzip
  - clipy
  - jd-gui
  - kitty
  - ferdi
  - font-monoid
  - microsoft-edge
  - postman
  - spotify
  - vagrant
  - visual-studio-code

homebrew_installed_packages:
  - automake
  - ansible-lint
  - coreutils
  - ctop
  - dockutil
  - gcc
  - gem-completion
  - git
  - gnu-tar
  - gradle
  - groovy
  - grunt-completion
  - htop
  - jenv
  - jq
  - k9s
  - mas
  - maven
  - maven-completion
  - node
  - openjdk@11
  - openshift-cli
  - openssl
  - packer
  - python@3.9
  - ranger
  - shellcheck
  - terraform
  - tmux
  - tldr
  - tree
  - vagrant-completion
  - watch
  - wget
