- hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags:
        - brew

  tasks:
    - name: Checkout repository
      ansible.builtin.git:
        repo: '{{ dotfiles_repository }}'
        dest: '{{ projects_path }}/dotfiles'
        version: 'main'
        update: yes
      tags:
        - dotfiles 
        - shell

    # Setup shell
    - import_tasks: tasks/setup/shell.yml
      tags:
        - shell

    # Import dotfiles
    - import_tasks: tasks/setup/dotfiles.yml
      tags:
        - dotfiles


