- name: fetch alacritty info file
  get_url: 
    url: https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info
    dest: /tmp/alacritty.info

- name: setup terminfo
  command: tic -xe alacritty,alacritty-direct /tmp/alacritty.info
  changed_when: false
  become: true

- name: Get fish path
  command: which fish
  register: which
  changed_when: false

- name: Add fish shell to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: '{{ which.stdout }}'
    backup: true
  become: true

- name: Set shell
  user:
    name: "yentlfrickx"
    shell: '{{ which.stdout }}'
  become: true

- name: Check if omf is installed for fish users
  stat:
    path: "~/.local/share/omf"
  register: omf_user_status

- name: Download omf installer
  get_url: 
    url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install 
    dest: /tmp/omf_install
  when: not omf_user_status.stat.exists
    
# Setup omf
- name: Setup omf
  command: 'fish /tmp/omf_install -y --noninteractive'
  changed_when: false
  when: not omf_user_status.stat.exists

- name: Install omf plugins
  command: "fish -c 'omf install {{ item }}'"
  loop: '{{ omf_packages }}'
  changed_when: false

- name: Set omf omf_theme
  command: "fish -c 'omf theme {{ omf_theme }}'"
  changed_when: false